package com.galvanize;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Arrays;

public class App {

            public static void main(String[] args) {

                InPersonCourse History = new InPersonCourse(Arrays.asList("Maggie", "Doug", "Bill"), "Fred");

                System.out.println(
                        History.getDescription()
                );

            }

}
