package com.galvanize;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        CompiledProgrammingLanguage Java = new CompiledProgrammingLanguage();

        Java.setName("Java");
        Java.setCompilerCommand("javac");



        System.out.println(

                Java.toString()
        );

    }
}
